 import { useState } from 'react';
 import { RecordingData } from '@/types/recording';
 import { Button } from '@/components/ui/button';
 import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
 import { Download, Copy, Check } from 'lucide-react';
 
 interface ExportPanelProps {
   recordingData: RecordingData;
 }
 
 export function ExportPanel({ recordingData }: ExportPanelProps) {
   const [copied, setCopied] = useState(false);
   const [activeTab, setActiveTab] = useState('ahk');
 
  const generateAutoHotkey = (): string => {
    // Build compacted data string: "x,y,delay|x,y,delay|..."
    let lastTimestamp = 0;
    const dataPoints: string[] = [];
    
    recordingData.points.forEach((point, index) => {
      const delay = index > 0 ? Math.round(point.timestamp - lastTimestamp) : 0;
      lastTimestamp = point.timestamp;
      const x = Math.round(point.x);
      const y = Math.round(point.y);
      dataPoints.push(`${x},${y},${delay}`);
    });
    
    const coordsString = dataPoints.join('|');
    const duration = recordingData.points.length > 0 
      ? Math.round(recordingData.points[recordingData.points.length - 1].timestamp) 
      : 0;
    
    const lines = [
      '; ===================================',
      '; Mouse Movement Script (Compacted)',
      '; Generated by Mouse Motion Recorder',
      '; ===================================',
      '; Pontos: ' + recordingData.points.length,
      '; Duração: ' + (duration / 1000).toFixed(2) + 's',
      '',
      '#SingleInstance Force',
      '#NoEnv',
      'SetBatchLines, -1',
      'CoordMode, Mouse, Screen',
      '',
      `coords := "${coordsString}"`,
      '',
      'F5::',
      '  MouseGetPos, startX, startY',
      '  Loop, Parse, coords, |',
      '  {',
      '    parts := StrSplit(A_LoopField, ",")',
      '    x := parts[1]',
      '    y := parts[2]',
      '    delay := parts[3]',
      '    if (delay > 0)',
      '      Sleep, %delay%',
      '    MouseMove, % startX + x, % startY - y, 0',
      '  }',
      'Return',
      '',
      'Escape::ExitApp',
    ];

    return lines.join('\n');
  };
 
  const generateLua = (): string => {
    const duration = recordingData.points.length > 0 
      ? Math.round(recordingData.points[recordingData.points.length - 1].timestamp) 
      : 0;
    
    // Build compacted data table: { {x,y,delay}, {x,y,delay}, ... }
    let lastTimestamp = 0;
    const moveEntries: string[] = [];
    
    recordingData.points.forEach((point, index) => {
      const delay = index > 0 ? Math.round(point.timestamp - lastTimestamp) : 0;
      lastTimestamp = point.timestamp;
      const x = Math.round(point.x);
      const y = Math.round(point.y);
      moveEntries.push(`{${x},${y},${delay}}`);
    });
    
    const lines = [
      '-- ===================================',
      '-- Mouse Movement Script (Logitech)',
      '-- Generated by Mouse Motion Recorder',
      '-- ===================================',
      '-- Pontos: ' + recordingData.points.length,
      '-- Duração: ' + (duration / 1000).toFixed(2) + 's',
      '',
      'local moves = {',
      '  ' + moveEntries.join(','),
      '}',
      '',
      'function OnEvent(event, arg)',
      '  if event == "MOUSE_BUTTON_PRESSED" and arg == 5 then',
      '    local startX, startY = GetMousePosition()',
      '    for i, v in ipairs(moves) do',
      '      if v[3] > 0 then Sleep(v[3]) end',
      '      MoveMouseTo(startX + v[1], startY - v[2])',
      '    end',
      '  end',
      'end',
    ];

    return lines.join('\n');
  };
 
   const getCode = () => {
     return activeTab === 'ahk' ? generateAutoHotkey() : generateLua();
   };
 
   const copyToClipboard = async () => {
     await navigator.clipboard.writeText(getCode());
     setCopied(true);
     setTimeout(() => setCopied(false), 2000);
   };
 
   const downloadFile = () => {
     const code = getCode();
     const extension = activeTab === 'ahk' ? 'ahk' : 'lua';
     const mimeType = 'text/plain';
     
     const blob = new Blob([code], { type: mimeType });
     const url = URL.createObjectURL(blob);
     const a = document.createElement('a');
     a.href = url;
     a.download = `mouse_movement.${extension}`;
     a.click();
     URL.revokeObjectURL(url);
   };
 
   return (
     <div className="bg-card rounded-xl p-6 space-y-4 border border-border fade-in">
       <h3 className="font-semibold text-lg flex items-center gap-2">
         <Download className="w-5 h-5 text-primary" />
         Exportar Script
       </h3>
 
       <Tabs value={activeTab} onValueChange={setActiveTab}>
         <TabsList className="grid w-full grid-cols-2">
           <TabsTrigger value="ahk">AutoHotkey</TabsTrigger>
           <TabsTrigger value="lua">Lua</TabsTrigger>
         </TabsList>
 
         <TabsContent value="ahk" className="mt-4">
           <div className="bg-muted rounded-lg p-4 max-h-64 overflow-auto">
             <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
               {generateAutoHotkey()}
             </pre>
           </div>
         </TabsContent>
 
         <TabsContent value="lua" className="mt-4">
           <div className="bg-muted rounded-lg p-4 max-h-64 overflow-auto">
             <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
               {generateLua()}
             </pre>
           </div>
         </TabsContent>
       </Tabs>
 
       <div className="flex gap-3">
         <Button onClick={copyToClipboard} variant="secondary" className="flex-1 gap-2">
           {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
           {copied ? 'Copiado!' : 'Copiar'}
         </Button>
         <Button onClick={downloadFile} className="flex-1 gap-2 bg-primary hover:bg-primary/90 text-primary-foreground">
           <Download className="w-4 h-4" />
           Baixar
         </Button>
       </div>
 
       <p className="text-xs text-muted-foreground">
         {activeTab === 'ahk' 
           ? 'Salve como .ahk e execute com AutoHotkey instalado.'
           : 'Adapte as funções moveMouse() e sleep() para seu ambiente.'}
       </p>
     </div>
   );
 }