 import { useState } from 'react';
 import { RecordingData } from '@/types/recording';
 import { Button } from '@/components/ui/button';
 import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
 import { Download, Copy, Check } from 'lucide-react';
 
 interface ExportPanelProps {
   recordingData: RecordingData;
 }
 
 export function ExportPanel({ recordingData }: ExportPanelProps) {
   const [copied, setCopied] = useState(false);
   const [activeTab, setActiveTab] = useState('ahk');
 
  const generateAutoHotkey = (): string => {
    // Build array entries: [dx, dy, delay]
    let lastTimestamp = 0;
    const entries: string[] = [];
    
    recordingData.points.forEach((point, index) => {
      const delay = index > 0 ? Math.round(point.timestamp - lastTimestamp) : 0;
      lastTimestamp = point.timestamp;
      const x = Math.round(point.x);
      const y = Math.round(point.y);
      entries.push(`[${x},${y},${delay}]`);
    });
    
    // Break into rows of 6 entries for readability
    const entriesPerRow = 6;
    const rows: string[] = [];
    for (let i = 0; i < entries.length; i += entriesPerRow) {
      rows.push('  ' + entries.slice(i, i + entriesPerRow).join(','));
    }
    
    const duration = recordingData.points.length > 0 
      ? Math.round(recordingData.points[recordingData.points.length - 1].timestamp) 
      : 0;
    
    const lines = [
      '; ===================================',
      '; Mouse Movement Script (AHK v2)',
      '; Generated by Mouse Motion Recorder',
      '; ===================================',
      '; Pontos: ' + recordingData.points.length,
      '; Duração: ' + (duration / 1000).toFixed(2) + 's',
      '',
      '#Requires AutoHotkey v2.0',
      '#SingleInstance Force',
      'CoordMode "Mouse", "Screen"',
      '',
      'global isPlaying := false',
      '',
      'pattern := [',
      rows.join(',\n'),
      ']',
      '',
      'PlayPattern(p) {',
      '  global isPlaying',
      '  MouseGetPos(&startX, &startY)',
      '  for move in p {',
      '    if !isPlaying',
      '      return',
      '    if move[3] > 0',
      '      Sleep(move[3])',
      '    MouseMove(startX + move[1], startY - move[2], 0)',
      '  }',
      '  isPlaying := false',
      '}',
      '',
      'F5:: {',
      '  global isPlaying',
      '  if isPlaying',
      '    return',
      '  isPlaying := true',
      '  PlayPattern(pattern)',
      '}',
      '',
      'Escape:: {',
      '  global isPlaying',
      '  isPlaying := false',
      '}',
    ];

    return lines.join('\n');
  };
 
  const generateLua = (): string => {
    const duration = recordingData.points.length > 0 
      ? Math.round(recordingData.points[recordingData.points.length - 1].timestamp) 
      : 0;
    
    // Build table entries: {dx, dy, delay}
    let lastTimestamp = 0;
    const entries: string[] = [];
    
    recordingData.points.forEach((point, index) => {
      const delay = index > 0 ? Math.round(point.timestamp - lastTimestamp) : 0;
      lastTimestamp = point.timestamp;
      const x = Math.round(point.x);
      const y = Math.round(point.y);
      entries.push(`{${x},${y},${delay}}`);
    });
    
    // Break into rows of 6 entries for readability
    const entriesPerRow = 6;
    const rows: string[] = [];
    for (let i = 0; i < entries.length; i += entriesPerRow) {
      rows.push('  ' + entries.slice(i, i + entriesPerRow).join(','));
    }
    
    const lines = [
      '-- ===================================',
      '-- Mouse Movement Script (Logitech)',
      '-- Generated by Mouse Motion Recorder',
      '-- ===================================',
      '-- Pontos: ' + recordingData.points.length,
      '-- Duração: ' + (duration / 1000).toFixed(2) + 's',
      '',
      'local pattern = {',
      rows.join(',\n'),
      '}',
      '',
      'local function PlayPattern(p, btn)',
      '  local startX, startY = GetMousePosition()',
      '  for i, m in ipairs(p) do',
      '    if not IsMouseButtonPressed(btn) then return end',
      '    if m[3] > 0 then Sleep(m[3]) end',
      '    MoveMouseTo(startX + m[1], startY - m[2])',
      '  end',
      'end',
      '',
      'function OnEvent(event, arg)',
      '  if event == "MOUSE_BUTTON_PRESSED" and arg == 5 then',
      '    PlayPattern(pattern, arg)',
      '  end',
      'end',
    ];

    return lines.join('\n');
  };
 
   const getCode = () => {
     return activeTab === 'ahk' ? generateAutoHotkey() : generateLua();
   };
 
   const copyToClipboard = async () => {
     await navigator.clipboard.writeText(getCode());
     setCopied(true);
     setTimeout(() => setCopied(false), 2000);
   };
 
   const downloadFile = () => {
     const code = getCode();
     const extension = activeTab === 'ahk' ? 'ahk' : 'lua';
     const mimeType = 'text/plain';
     
     const blob = new Blob([code], { type: mimeType });
     const url = URL.createObjectURL(blob);
     const a = document.createElement('a');
     a.href = url;
     a.download = `mouse_movement.${extension}`;
     a.click();
     URL.revokeObjectURL(url);
   };
 
   return (
     <div className="bg-card rounded-xl p-6 space-y-4 border border-border fade-in">
       <h3 className="font-semibold text-lg flex items-center gap-2">
         <Download className="w-5 h-5 text-primary" />
         Exportar Script
       </h3>
 
       <Tabs value={activeTab} onValueChange={setActiveTab}>
         <TabsList className="grid w-full grid-cols-2">
           <TabsTrigger value="ahk">AutoHotkey</TabsTrigger>
           <TabsTrigger value="lua">Lua</TabsTrigger>
         </TabsList>
 
         <TabsContent value="ahk" className="mt-4">
           <div className="bg-muted rounded-lg p-4 max-h-64 overflow-auto">
             <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
               {generateAutoHotkey()}
             </pre>
           </div>
         </TabsContent>
 
         <TabsContent value="lua" className="mt-4">
           <div className="bg-muted rounded-lg p-4 max-h-64 overflow-auto">
             <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
               {generateLua()}
             </pre>
           </div>
         </TabsContent>
       </Tabs>
 
       <div className="flex gap-3">
         <Button onClick={copyToClipboard} variant="secondary" className="flex-1 gap-2">
           {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
           {copied ? 'Copiado!' : 'Copiar'}
         </Button>
         <Button onClick={downloadFile} className="flex-1 gap-2 bg-primary hover:bg-primary/90 text-primary-foreground">
           <Download className="w-4 h-4" />
           Baixar
         </Button>
       </div>
 
       <p className="text-xs text-muted-foreground">
         {activeTab === 'ahk' 
           ? 'Salve como .ahk e execute com AutoHotkey instalado.'
           : 'Adapte as funções moveMouse() e sleep() para seu ambiente.'}
       </p>
     </div>
   );
 }