 import { useState } from 'react';
 import { RecordingData } from '@/types/recording';
 import { Button } from '@/components/ui/button';
 import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
 import { Download, Copy, Check } from 'lucide-react';
 
 interface ExportPanelProps {
   recordingData: RecordingData;
 }
 
 export function ExportPanel({ recordingData }: ExportPanelProps) {
   const [copied, setCopied] = useState(false);
   const [activeTab, setActiveTab] = useState('ahk');
 
   const generateAutoHotkey = (): string => {
     const lines = [
       '; ===================================',
       '; Mouse Movement Script',
       '; Generated by Mouse Motion Recorder',
       '; ===================================',
       '; ',
       '; Este script move o mouse seguindo os movimentos gravados.',
       '; Os valores são relativos à posição inicial do mouse.',
       '; ',
       '; Instruções:',
       '; 1. Posicione o mouse onde deseja iniciar',
       '; 2. Pressione F5 para executar',
       '; 3. Pressione Escape para cancelar',
       '; ',
       '',
       '#SingleInstance Force',
       '#NoEnv',
       'SetBatchLines, -1',
       'CoordMode, Mouse, Screen',
       '',
       'F5::',
       '  MouseGetPos, startX, startY',
       '  ',
     ];
 
     let lastTimestamp = 0;
     
     recordingData.points.forEach((point, index) => {
       const delay = point.timestamp - lastTimestamp;
       lastTimestamp = point.timestamp;
       
       if (delay > 0 && index > 0) {
         lines.push(`  Sleep, ${delay}`);
       }
       
       lines.push(`  MouseMove, % startX + ${point.x.toFixed(0)}, % startY - ${point.y.toFixed(0)}, 0`);
     });
 
     lines.push('Return');
     lines.push('');
     lines.push('Escape::ExitApp');
 
     return lines.join('\n');
   };
 
   const generateLua = (): string => {
     const lines = [
       '-- ===================================',
       '-- Mouse Movement Script',
       '-- Generated by Mouse Motion Recorder',
       '-- ===================================',
       '-- ',
       '-- Este script move o mouse seguindo os movimentos gravados.',
       '-- Os valores são relativos à posição inicial do mouse.',
       '-- ',
       '-- Compatível com: LuaMacros, AutoKey, ou outras engines Lua.',
       '-- ',
       '',
       '-- Função auxiliar para mover o mouse',
       '-- Substitua pela função apropriada do seu ambiente',
       'local function moveMouse(x, y)',
       '  -- Exemplo: mouse.move(x, y)',
       '  print(string.format("Move to: %d, %d", x, y))',
       'end',
       '',
       'local function sleep(ms)',
       '  -- Exemplo: os.execute("sleep " .. ms/1000)',
       '  -- ou use a função de sleep do seu ambiente',
       'end',
       '',
       '-- Dados do movimento',
       'local movements = {',
     ];
 
     recordingData.points.forEach((point, index) => {
       const isLast = index === recordingData.points.length - 1;
       lines.push(`  { x = ${point.x.toFixed(0)}, y = ${point.y.toFixed(0)}, t = ${point.timestamp} }${isLast ? '' : ','}`);
     });
 
     lines.push('}');
     lines.push('');
     lines.push('-- Execução do movimento');
     lines.push('local function executeMovement(startX, startY)');
     lines.push('  local lastTime = 0');
     lines.push('  ');
     lines.push('  for _, point in ipairs(movements) do');
     lines.push('    local delay = point.t - lastTime');
     lines.push('    lastTime = point.t');
     lines.push('    ');
     lines.push('    if delay > 0 then');
     lines.push('      sleep(delay)');
     lines.push('    end');
     lines.push('    ');
     lines.push('    moveMouse(startX + point.x, startY - point.y)');
     lines.push('  end');
     lines.push('end');
     lines.push('');
     lines.push('-- Para executar, chame:');
     lines.push('-- executeMovement(posição_inicial_x, posição_inicial_y)');
 
     return lines.join('\n');
   };
 
   const getCode = () => {
     return activeTab === 'ahk' ? generateAutoHotkey() : generateLua();
   };
 
   const copyToClipboard = async () => {
     await navigator.clipboard.writeText(getCode());
     setCopied(true);
     setTimeout(() => setCopied(false), 2000);
   };
 
   const downloadFile = () => {
     const code = getCode();
     const extension = activeTab === 'ahk' ? 'ahk' : 'lua';
     const mimeType = 'text/plain';
     
     const blob = new Blob([code], { type: mimeType });
     const url = URL.createObjectURL(blob);
     const a = document.createElement('a');
     a.href = url;
     a.download = `mouse_movement.${extension}`;
     a.click();
     URL.revokeObjectURL(url);
   };
 
   return (
     <div className="bg-card rounded-xl p-6 space-y-4 border border-border fade-in">
       <h3 className="font-semibold text-lg flex items-center gap-2">
         <Download className="w-5 h-5 text-primary" />
         Exportar Script
       </h3>
 
       <Tabs value={activeTab} onValueChange={setActiveTab}>
         <TabsList className="grid w-full grid-cols-2">
           <TabsTrigger value="ahk">AutoHotkey</TabsTrigger>
           <TabsTrigger value="lua">Lua</TabsTrigger>
         </TabsList>
 
         <TabsContent value="ahk" className="mt-4">
           <div className="bg-muted rounded-lg p-4 max-h-64 overflow-auto">
             <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
               {generateAutoHotkey()}
             </pre>
           </div>
         </TabsContent>
 
         <TabsContent value="lua" className="mt-4">
           <div className="bg-muted rounded-lg p-4 max-h-64 overflow-auto">
             <pre className="text-xs font-mono text-muted-foreground whitespace-pre-wrap">
               {generateLua()}
             </pre>
           </div>
         </TabsContent>
       </Tabs>
 
       <div className="flex gap-3">
         <Button onClick={copyToClipboard} variant="secondary" className="flex-1 gap-2">
           {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
           {copied ? 'Copiado!' : 'Copiar'}
         </Button>
         <Button onClick={downloadFile} className="flex-1 gap-2 bg-primary hover:bg-primary/90 text-primary-foreground">
           <Download className="w-4 h-4" />
           Baixar
         </Button>
       </div>
 
       <p className="text-xs text-muted-foreground">
         {activeTab === 'ahk' 
           ? 'Salve como .ahk e execute com AutoHotkey instalado.'
           : 'Adapte as funções moveMouse() e sleep() para seu ambiente.'}
       </p>
     </div>
   );
 }